---
version: "3"

services:
  gophish-proxy:
    image: nginx:alpine
    volumes:
      - ./proxies:/etc/nginx/conf.d/
      - ./ssl:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
      - 3443:3443

  gophish:
    restart: unless-stopped
    build: .
    volumes:
      - ./gophish/config.json:/opt/gophish/config.json
    expose:
      - 80
      - 3333
