---
version: "3"

services:
  gophish-proxy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./caddy:/etc/caddy
    ports:
      - 80:80
      - 443:443
      - 3443:3443

  gophish:
    build: .
    restart: unless-stopped
    volumes:
      - ./gophish/config.json:/opt/gophish/config.json
    expose:
      - 80
      - 3333
